### ISSUE TITLE
Spotify LED Matrix Epic

### ISSUE THREAD

**Issue by austindriggs** [austindriggs/spotify-led-matrix#14]
## SUMMARY

Summarize the issue in 1-3 sentences.

### Order of issues:

* [ ] #1 Pick out the display
* [ ] #2 Pick out the microcontroller
* [ ] #3 Pick out the hardware features
* Design the schematic
* [ ] #10 Design the ESP32 Circuit
* [ ] #12 Design the programming USB to UART circuit
* [ ] #11 Design the rotary encoder circuit
* [ ] #13 Design everything else in the schematic

## DESCRIPTION

Describe the general work completed and why the tasks were performed.

## NOTES

Put any additional notes here.

## SUPPORT

List any resources or supporting images here.
